# Generated by Django 3.0.3 on 2020-07-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_cards_app', '0004_auto_20200719_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='qty_2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='val_2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
