# Generated by Django 3.0.3 on 2020-07-19 12:07

from django.db import migrations, models
import gift_cards_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_cards_app', '0006_auto_20200719_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='first_name',
            field=models.CharField(max_length=30, validators=[gift_cards_app.models.Orders.no_spaces]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='last_name',
            field=models.CharField(max_length=30, validators=[gift_cards_app.models.Orders.no_spaces]),
        ),
    ]
