# Generated by Django 3.0.3 on 2020-07-19 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_cards_app', '0007_auto_20200719_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
