# Generated by Django 3.0.3 on 2020-07-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_cards_app', '0008_auto_20200719_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='date',
            new_name='order_date',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
